// [Rules | ESLint Plugin Perfectionist](https://perfectionist.dev/rules)

let perfectionistConfig = {
	'perfectionist/sort-array-includes': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: ['literal'],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionist/sort-classes': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [
				'index-signature',
				['static-property', 'static-accessor-property'],
				['static-get-method', 'static-set-method'],
				['protected-static-property', 'protected-static-accessor-property'],
				['protected-static-get-method', 'protected-static-set-method'],
				['private-static-property', 'private-static-accessor-property'],
				['private-static-get-method', 'private-static-set-method'],
				'static-block',
				['property', 'accessor-property'],
				['get-method', 'set-method'],
				['protected-property', 'protected-accessor-property'],
				['protected-get-method', 'protected-set-method'],
				['private-property', 'private-accessor-property'],
				['private-get-method', 'private-set-method'],
				'constructor',
				['static-method', 'static-function-property'],
				['protected-static-method', 'protected-static-function-property'],
				['private-static-method', 'private-static-function-property'],
				['method', 'function-property'],
				['protected-method', 'protected-function-property'],
				['private-method', 'private-function-property'],
				'unknown',
			],
			ignoreCallbackDependenciesPatterns: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-exports': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-heritage-clauses': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-interfaces': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { sortBy: 'name', type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			sortBy: 'name',
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionist/sort-intersection-types': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-maps': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionist/sort-named-exports': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreAlias: false,
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-object-types': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { sortBy: 'name', type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			sortBy: 'name',
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionist/sort-sets': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: ['literal'],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
			useConfigurationIf: {},
		},
	],
	'perfectionist/sort-switch-case': [
		'error',
		{
			alphabet: '',
			fallbackSort: { type: 'unsorted' },
			ignoreCase: true,
			locales: 'en-US',
			order: 'asc',
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
	'perfectionist/sort-union-types': [
		'error',
		{
			alphabet: '',
			customGroups: [],
			fallbackSort: { type: 'unsorted' },
			groups: [],
			ignoreCase: true,
			locales: 'en-US',
			newlinesBetween: 'ignore',
			newlinesInside: 'newlinesBetween',
			order: 'asc',
			partitionByComment: false,
			partitionByNewLine: false,
			specialCharacters: 'keep',
			type: 'natural',
		},
	],
};

export { perfectionistConfig };
